### ISSUE TITLE
Can't import rules

### ISSUE THREAD

**Issue by sdawodu** [dfunckt/django-rules#42]
with django-rules imported from pip:
```
....
Django==1.8.5
django-rules==0.2
django-social-auth==0.7.28
django-wysiwyg-redactor==0.4.9.1
djangorestframework==3.4.7
httplib2==0.9.2
...
```

and rules included in my INSTALLED_APPS
```
INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rules.apps.AutodiscoverRulesConfig',
    'rest_framework.authtoken',
    'rest_framework',
    'accounts',
    'bms',
    'cms',
    'socialmedia',
    # 'v1_api',
)
```

Attempting to start the django shell, I get the following error

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 325, in execute
    django.setup()
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/apps/config.py", line 112, in create
    mod = import_module(mod_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named rules.apps

```

I can't think of what might be wrong..

**Comment by sdawodu** [comment]
Discovered my error. I had installed the wrong package.

Installed django-rules via pip not rules. That points to  http://github.com/maraujop/django-rules instead.

Leaving this here in case someone else is as silly as me
