### ISSUE TITLE
ImportError on python 2.7.10

### ISSUE THREAD

**Issue by jab3z** [dfunckt/django-rules#53]
Hello,

I'm getting the following error (I didn't install the other package, django-rules, 🤐 ) on Django 1.9.

```
Unhandled exception in thread started by <function wrapper at 0x104001758>
Traceback (most recent call last):
  File "/Users/dacian/.virtualenvs/venv/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/dacian/.virtualenvs/venv/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/Users/dacian/.virtualenvs/venv/lib/python2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/Users/dacian/.virtualenvs/venv/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/dacian/.virtualenvs/venv/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/dacian/.virtualenvs/venv/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/dacian/.virtualenvs/venv/lib/python2.7/site-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/dacian/Desktop/dev/project_name/extras/dashboard/rules.py", line 6, in <module>
    from rules import predicate
ImportError: cannot import name predicate
```

```
INSTALLED_APPS = [
    'modeltranslation',
    'django.contrib.sites',
    'jet',
    'django.contrib.admin',
    'django.contrib.auth',
    'polymorphic',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    # 'rules',
    'rules.apps.AutodiscoverRulesConfig',
    'django_extensions',
    'rest_framework',
]
```
**extras/dashboard/rules.py** 
```
# -*- coding: utf-8 -*-

from __future__ import absolute_import
from __future__ import unicode_literals

from rules import predicate


@predicate(name='has_menu_perm')
def has_menu_perm(user, menu_item):
    return any([user.has_perm(perm) for perm in menu_item.perms])
```

**Comment by dfunckt** [comment]
Try adding `from __future__ import absolute_import` to `/Users/dacian/Desktop/dev/project_name/extras/dashboard/rules.py`. That should do it.

**Comment by jab3z** [comment]
But, it's already there 😞

**Comment by dfunckt** [comment]
Can you paste the contents of `/Users/dacian/Desktop/dev/project_name/extras/dashboard/rules.py`?

**Comment by jab3z** [comment]
I have edited the first post.

**Comment by dfunckt** [comment]
Right. Can you please add `import sys; print(sys.path)` as the first statement in `extras/dashboard/rules.py`, run and paste here the output? IT's possible `extras/dashboard` is in your Python path before site-packages or wherever rules is installed at.

**Comment by jab3z** [comment]
It got printed 4 times

```
['/Users/dacian/Desktop/dev/project_name', 
 '/Users/dacian/.virtualenvs/venv/lib/python2.7/site-packages/_pdbpp_path_hack', 
 '/Users/dacian/Desktop/dev/project_name/extras', 
 '/Users/dacian/Desktop/dev/project_name/extras/dashboard/bulk', 
 '/Users/dacian/Desktop/dev/project_name/plugins/shopify', 
 '/Users/dacian/Desktop/dev/project_name', 
 '/Users/dacian/Desktop/dev/project_name/plugins', 
 '/Users/dacian/Desktop/dev/project_name/legacy', 
 '/Users/dacian/Desktop/dev/project_name/gateway/m', 
 '/Users/dacian/Desktop/dev/project_name/gateway/p', 
 '/Users/dacian/Desktop/dev/project_name/gateway/templatetags', 
 '/Users/dacian/Desktop/dev/project_name/extras/account', 
 '/Users/dacian/Desktop/dev/project_name/gateway/c', 
 '/Users/dacian/Desktop/dev/project_name/gateway/m', 
 '/Users/dacian/Desktop/dev/project_name/extras/dashboard/migrations', 
 '/Users/dacian/Desktop/dev/project_name/extras/dashboard', 
 '/Users/dacian/Desktop/dev/project_name/gateway/models', 
 '/Users/dacian/Desktop/dev/project_name/gateway/k', 
 '/Users/dacian/Desktop/dev/project_name/gateway', 
 '/Users/dacian/Desktop/dev/project_name/gateway/migrations', 
 '/Users/dacian/Desktop/dev/project_name/extras/request', 
 '/Users/dacian/Desktop/dev/project_name/gateway/b', 
 '/Users/dacian/Desktop/dev/project_name/extras/ui', 
 '/Users/dacian/Desktop/dev/project_name/sms', 
 '/Users/dacian/Desktop/dev/project_name/gateway/tests', 
 '/Users/dacian/Desktop/dev/project_name/api', 
 '/Users/dacian/Desktop/dev/project_name/extras/currency', 
 '/Users/dacian/Desktop/dev/project_name/config', 
 '/Users/dacian/.virtualenvs/venv/lib/python27.zip', 
 '/Users/dacian/.virtualenvs/venv/lib/python2.7', 
 '/Users/dacian/.virtualenvs/venv/lib/python2.7/plat-darwin', 
 '/Users/dacian/.virtualenvs/venv/lib/python2.7/plat-mac', 
 '/Users/dacian/.virtualenvs/venv/lib/python2.7/plat-mac/lib-scriptpackages', 
 '/Users/dacian/.virtualenvs/venv/lib/python2.7/lib-tk', 
 '/Users/dacian/.virtualenvs/venv/lib/python2.7/lib-old', 
 '/Users/dacian/.virtualenvs/venv/lib/python2.7/lib-dynload', 
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', 
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', 
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', 
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', 
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', 
 '/Users/dacian/.virtualenvs/venv/lib/python2.7/site-packages', 
 '/Users/dacian/Desktop/dev/project_name/config'
 ]
```

**Comment by jab3z** [comment]
> IT's possible extras/dashboard is in your Python path before site-packages or wherever rules is installed at.

If that was the case, the issue shouldn't happen to all installed packages?

**Comment by dfunckt** [comment]
> If that was the case, the issue shouldn't happen to all installed packages?

It would happen for all modules with the same name, such as `django-rules` and your `rules.py`. In this case, your rules.py file is accessible due to ''/Users/dacian/Desktop/dev/project_name/extras/dashboard' before django-rules.

Can you try adding the following to your `settings.py` and see if that resolves the issue?

```
import sys; sys.path.insert(0, '/Users/dacian/.virtualenvs/venv/lib/python2.7/site-packages')
```

**Comment by jab3z** [comment]
Thanks, works on local, altough I didn't push yet to dev server. Any hints of how to manage this in production?

**Comment by dfunckt** [comment]
I suspect you manually modify the path, in which case you may simply not add `/Users/dacian/Desktop/dev/project_name/extras/dashboard` and it'll work everywhere.

In any case, you shouldn't be adding *nested* paths in your Python path, because you can end up with hard to debug issues like this. Django already adds your project to path (i.e. `/Users/dacian/Desktop/dev/project_name`) and, in my opinion, that should be enough to import any modules from your project.

Closing for now, you're welcome to reopen if you hit further issues.
